let studentFirstName = "Brandon";
let studentLastName = "N";
let grade1 = 53;
let grade2 = 96;
let grade3 = 65;
let grade4 = 74;
let passingGrade = 80;
const total = grade1 + grade2 + grade3 + grade4;
const average = total / 4;
studentLastName = "Newman";
console.log(`${studentFirstName} ${studentLastName} has an average grade of  ${average}`);
console.log(`Pass? ${average >= passingGrade}`);
